# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Comment

# Model Form Field configuration
form: $/october/test/models/comment/fields_test.yaml

# Model Class name
modelClass: October\Test\Models\Comment

# Default redirect location
defaultRedirect: october/test/comments

# Create page
create:
    title: backend::lang.form.create_title
    redirect: october/test/comments/update/:id
    redirectClose: october/test/comments

# Update page
update:
    title: backend::lang.form.update_title
    redirect: october/test/comments
    redirectClose: october/test/comments

# Preview page
preview:
    title: backend::lang.form.preview_title
