# ===================================
#  Relation Behavior Config
# ===================================

comments:
    label: Comment
    list: $/october/test/models/comment/columns.yaml
    form: $/october/test/models/comment/fields.yaml
    readOnly: true
    view:
        filter: $/october/test/models/comment/scopes.yaml
        toolbarButtons: add|link|unlink|delete
    manage:
        context: relation
        recordsPerPage: 10
        showSearch: true

status:
    label: Status
    form: $/october/test/models/attribute/fields.yaml
    list: $/october/test/models/attribute/columns.yaml
    view:
        toolbarButtons: link|unlink

galleries:
    label: Galleries
    view:
        list: $/october/test/models/gallery/columns.yaml
        toolbarButtons: create|link|delete|unlink
        defaultSort:
            column: title
            direction: asc
    manage:
        form: $/october/test/models/gallery/fields_simple.yaml

galleries_pivot:
    label: Galleries
    view:
        list: $/october/test/models/gallery/columns.yaml
        toolbarButtons: link|unlink
    manage:
        form: $/october/test/models/gallery/fields_simple.yaml
    pivot:
        form:
            fields:
                pivot[commission_amount]:
                    label: Commission Amount
                    commentAbove: 'in %'

review:
    label: Review
    view:
        form: $/october/test/models/review/fields_simple.yaml
        list: $/october/test/models/review/columns.yaml
    manage:
        form: $/october/test/models/review/fields_simple.yaml